### ISSUE TITLE
Docs: a way to use?

### ISSUE THREAD

**Issue by sebastianjnuwu** [mayank0274/api-tester#1]
In the readme you could leave a video or Gif of how to use the plugin because so people don't get lost!

**Comment by mayank0274** [comment]
added usage guide in readme.md check it out

**Comment by sebastianjnuwu** [comment]
Unfortunately it does not appear in my acode and your plugin is installed, strange!

**Comment by mayank0274** [comment]
[Check this](https://github.com/mayank0274/api-tester/blob/main/usage%20guide.gif) it is direct link of gif of how to use this plugin
