### ISSUE TITLE
Improve response

### ISSUE THREAD

**Issue by Jobians** [mayank0274/api-tester#4]
Please improve the response like JSON

**Comment by Jobians** [comment]
![Screenshot_20230908-113116](https://github.com/mayank0274/api-tester/assets/88005779/78a0dd4e-ae6f-4e9e-99fa-6027d65082fe)

**Comment by mayank0274** [comment]
Its already showing response in json 
![Uploading Screenshot_2023-09-08-16-51-38-78.jpg…]()

**Comment by mayank0274** [comment]
![Uploading Screenshot_2023-09-08-16-51-38-78.jpg…]()

**Comment by Jobians** [comment]
I didn't understand "try by using cors in your api file"

**Comment by mayank0274** [comment]
try by adding [this](https://www.npmjs.com/package/cors) 
package to your api server file

**Comment by Jobians** [comment]
Ok I got your point, but what if I'm sending request to external API

**Comment by mayank0274** [comment]
that also works fine, i used several api's for testing and they work properly, you can send me link of api in which you encountered issue i will look into it

**Comment by mayank0274** [comment]
> Ok I got your point, but what if I'm sending request to external API

A more specific answer to this question:
Sending request to external api's may subject to CORS policy.As Acode is cordova app which runs in webview you may face problem due to CORS while sending requests to external api's that allowed specific domains/website to access them.
